# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Jaeeun Seo
email: jaeeun.seo@northwestern.edu
affiliation: Northwestern University
url: "https://jaeeun-seo.github.io"
baseurl: ""        #
description: 'I am a Postdoctoral Scholar in the Department of Economics at Northwestern University. My research interests are in international trade, macroeconomics, and urban economics. I received my Ph.D. in Economics from MIT in 2024.'
mydescription: 'Welcome to my website! I am a Postdoctoral Scholar in the Department of Economics at Northwestern University. My research interests are in <span class="semi-bold">international trade</span>, <span class="semi-bold">macroeconomics</span>, and <span class="semi-bold">urban economics</span>. I received my Ph.D. in Economics from MIT in 2024.'
CV_file: "https://jaeeun-seo.github.io/files/Seo_CV.pdf"


# Build settings
lang: en
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
